language: python
cache:
  pip: true
  directories:
    - .eggs
python:
  - 3.9
install:
  - pip install Django
  - pip install beautifulsoup4
  - pip install requests
  - pip install flake8
  - pip install coveralls
before_script:
  - make lint
script: make test-with-coverage
after_success:
  - coveralls
